<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE agency [

	<!ELEMENT agency (ori)>
	<!ELEMENT ori (agency, state, division, county, offense, offender)> 

	<!ELEMENT onlinecanteen (#PCDATA)>
	<!ELEMENT webpage (#PCDATA)>
	<!ELEMENT navbar (#PCDATA)>
	<!ELEMENT contents (#PCDATA)>
	<!ELEMENT carousel (#PCDATA)>
	<!ELEMENT button (#PCDATA)>
	<!ELEMENT dropdown (#PCDATA)>
	<!ELEMENT footer (#PCDATA)>
	<!ELEMENT address (#PCDATA)>
	<!ELEMENT number (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT quicklinks (#PCDATA)>
	<!ELEMENT terms (#PCDATA)>
	<!ELEMENT privacy (#PCDATA)>
	<!ELEMENT help (#PCDATA)>
	<!ELEMENT questions (#PCDATA)>
	<!ELEMENT h4 (#PCDATA)>
	<!ELEMENT p (#PCDATA)>
	<!ELEMENT img (#PCDATA)>
	<!ELEMENT menu (#PCDATA)>
	<!ELEMENT breakfast (#PCDATA)>
	<!ELEMENT list (#PCDATA)>
	<!ELEMENT h2 (#PCDATA)>



	<!ATTLIST webpage id CDATA #REQUIRED>
	<!ATTLIST  navbar link CDATA #REQUIRED>
	<!ATTLIST navbar link  CDATA #REQUIRED>
	<!ATTLIST navbarfeature link CDATA #REQUIRED>
	<!ATTLIST navbar pagename CDATA #REQUIRED>
	<!ATTLIST dropdown link CDATA #REQUIRED>
	<!ATTLIST carousel name CDATA #REQUIRED>
	<!ATTLIST img name CDATA #REQUIRED>
	<!ATTLIST list price CDATA #REQUIRED>
]>



<onlinecanteen>

	<webpage id="home">
		<navbar link="index.php"> Home</navbar>
		<navbar link="about.php"> About</navbar>
		<navbar link="feature.php"> Feature</navbar>
		<navbar pagename="Menu">
			<dropdown link="breakfast.php">Breakfast</dropdown>
			<dropdown link="snacks.php">Snacks</dropdown>
			<dropdown link="lunch.php">Lunch</dropdown>
			<dropdown link="appetizers.php">Appetizer</dropdown>
			<dropdown link="drinks.php">Drinks</dropdown>
			<dropdown link="dessert.php">Dessert</dropdown>
	   </navbar>
	   <contents>
	   		<carousel name="welcome">Welcome to MSC's Online Canteen </carousel>
	   			<button name="first">View Menu</button>
	   			<button name="second">Reserve Table Menu</button>
	   		<footer>
	   			<address>Panfilo M. Manguera, Sr. Road, Boac, 4900 Marinduque</address>
	   			<number>09-1045-321-21</number>
	   			<email>msc@gmail.com</email>
	   			<quicklinks>
	   				<terms>Terms of Use</terms>
	   				<privacy>Privacy Policy</privacy>
	   				<cookies>Cookies</cookies>
	   				<help>Help</help>
	   				<questions>FAQS</questions>
	   				<newsletter>Lorem ipsum dolor sit amet elit. Quisque eu lectus a leo dictum nec non quam. Tortor eu placerat rhoncus, lorem quam iaculis felis, sed lacus neque id eros.</newsletter>
	   			</quicklinks>
	   		</footer>
	   </contents>
	</webpage>

<webpage id="about">
		<navbar link="index.php"> Home</navbar>
		<navbar link="about.php"> About</navbar>
		<navbar link="feature.php"> Feature</navbar>
		<navbar pagename="Menu">
			<dropdown link="breakfast.php">Breakfast</dropdown>
			<dropdown link="snacks.php">Snacks</dropdown>
			<dropdown link="lunch.php">Lunch</dropdown>
			<dropdown link="appetizers.php">Appetizer</dropdown>
			<dropdown link="drinks.php">Drinks</dropdown>
			<dropdown link="dessert.php">Dessert</dropdown>
	   </navbar>
	   <contents>
	   		<h4>About Us </h4>
	   			<p>HOME?ABOUT US</p>
	   			<img name="msc-logo">Marinduque State College Logo</img>
<footer>
	   			<address>Panfilo M. Manguera, Sr. Road, Boac, 4900 Marinduque</address>
	   			<number>09-1045-321-21</number>
	   			<email>msc@gmail.com</email>
	   			<quicklinks>
	   				<terms>Terms of Use</terms>
	   				<privacy>Privacy Policy</privacy>
	   				<cookies>Cookies</cookies>
	   				<help>Help</help>
	   				<questions>FAQS</questions>
	   				<newsletter>Lorem ipsum dolor sit amet elit. Quisque eu lectus a leo dictum nec non quam. Tortor eu placerat rhoncus, lorem quam iaculis felis, sed lacus neque id eros.</newsletter>
	   			</quicklinks>
	   		</footer>
	   </contents>
	</webpage>

	<webpage id="feature">
		<navbar link="index.php"> Home</navbar>
		<navbar link="about.php"> About</navbar>
		<navbar link="feature.php"> Feature</navbar>
		<navbar pagename="Menu">
			<dropdown link="breakfast.php">Breakfast</dropdown>
			<dropdown link="snacks.php">Snacks</dropdown>
			<dropdown link="lunch.php">Lunch</dropdown>
			<dropdown link="appetizers.php">Appetizer</dropdown>
			<dropdown link="drinks.php">Drinks</dropdown>
			<dropdown link="dessert.php">Dessert</dropdown>
	   </navbar>
	   <contents>
	   		<h4>FEATURES</h4>
	   			<p>HOME/FEATURES</p>
	   			<img name="feature">Our Key Features</img>

	<footer>
	   			<address>Panfilo M. Manguera, Sr. Road, Boac, 4900 Marinduque</address>
	   			<number>09-1045-321-21</number>
	   			<email>msc@gmail.com</email>
	   			<quicklinks>
	   				<terms>Terms of Use</terms>
	   				<privacy>Privacy Policy</privacy>
	   				<cookies>Cookies</cookies>
	   				<help>Help</help>
	   				<questions>FAQS</questions>
	   				<newsletter>Lorem ipsum dolor sit amet elit. Quisque eu lectus a leo dictum nec non quam. Tortor eu placerat rhoncus, lorem quam iaculis felis, sed lacus neque id eros.</newsletter>
	   			</quicklinks>
	   		</footer>
	   </contents>
	</webpage>

<webpage id="menu">
		<navbar link="index.php"> Home</navbar>
		<navbar link="about.php"> About</navbar>
		<navbar link="feature.php"> Feature</navbar>
		<navbar pagename="Menu">
			<dropdown link="breakfast.php">Breakfast</dropdown>
			<dropdown link="snacks.php">Snacks</dropdown>
			<dropdown link="lunch.php">Lunch</dropdown>
			<dropdown link="appetizers.php">Appetizer</dropdown>
			<dropdown link="drinks.php">Drinks</dropdown>
			<dropdown link="dessert.php">Dessert</dropdown>
	   </navbar>
	   <contents>
	   		<h4>MENU</h4>

	   			<menu>
	   				<breakfast>
	   					<list price="₱25.00">EGG FRIED RICE</list>
	   					<list price="₱50.00">HOTSILOG</list>
	   					<list price="₱50.00">LONGSILOG</list>
	   					<list price="₱65.00">TOPSILOG</list>
	   				</breakfast>
	   			</menu>


	<footer>
	   			<address>Panfilo M. Manguera, Sr. Road, Boac, 4900 Marinduque</address>
	   			<number>09-1045-321-21</number>
	   			<email>msc@gmail.com</email>
	   			<quicklinks>
	   				<terms>Terms of Use</terms>
	   				<privacy>Privacy Policy</privacy>
	   				<cookies>Cookies</cookies>
	   				<help>Help</help>
	   				<questions>FAQS</questions>
	   				<newsletter>Lorem ipsum dolor sit amet elit. Quisque eu lectus a leo dictum nec non quam. Tortor eu placerat rhoncus, lorem quam iaculis felis, sed lacus neque id eros.</newsletter>
	   			</quicklinks>
	   		</footer>
	   	</contents>
	</webpage>

	<webpage id="contact">
		<navbar link="index.php"> Home</navbar>
		<navbar link="about.php"> About</navbar>
		<navbar link="feature.php"> Feature</navbar>
		<navbar pagename="Menu">
			<dropdown link="breakfast.php">Breakfast</dropdown>
			<dropdown link="snacks.php">Snacks</dropdown>
			<dropdown link="lunch.php">Lunch</dropdown>
			<dropdown link="appetizers.php">Appetizer</dropdown>
			<dropdown link="drinks.php">Drinks</dropdown>
			<dropdown link="dessert.php">Dessert</dropdown>
	   </navbar>
	   <contents>
	   		<h4>CONTACT US </h4>
	   			<p>HOME/RESERVE A TABLE</p>
	   			<h2>CONTACT US FOR ANY QUERY</h2>
	   			<address>Panfilo M. Manguera, Sr. Road, Boac, 4900 Marinduque</address>
	   			<number>09-1045-321-21</number>
	   			<email>msc@gmail.com</email>


	<footer>
	   			<address>Panfilo M. Manguera, Sr. Road, Boac, 4900 Marinduque</address>
	   			<number>09-1045-321-21</number>
	   			<email>msc@gmail.com</email>
	   			<quicklinks>
	   				<terms>Terms of Use</terms>
	   				<privacy>Privacy Policy</privacy>
	   				<cookies>Cookies</cookies>
	   				<help>Help</help>
	   				<questions>FAQS</questions>
	   				<newsletter>Lorem ipsum dolor sit amet elit. Quisque eu lectus a leo dictum nec non quam. Tortor eu placerat rhoncus, lorem quam iaculis felis, sed lacus neque id eros.</newsletter>
	   			</quicklinks>
	   		</footer>
	   	</contents>
	</webpage>



</onlinecanteen>